--[[

    tests/unit/mmdb_test.lua

    Unit tests for core/mmdb.lua (#78 Phase D1). Validated against
    MaxMind's canonical test databases in fixtures/mmdb/ (produced by
    MaxMind's own mmdbwriter, not by our reader) with expected lookup
    values generated by the reference `maxminddb` Python reader v3.1.1.
    This keeps the validation non-circular: a bug shared between our
    encoder and decoder is impossible because we ship no encoder.

    Coverage:
      - open(): bad-arg / missing-file / non-MMDB error returns
      - metadata parse for all three record sizes (24 / 28 / 32)
      - full data-type decode (decoder.mmdb: map, array, uint16/32/64,
        uint128, int32, string, bytes, double, float, boolean, nested
        map, pointer-dedup)
      - IPv4-native tree traversal + clean miss (ipv4-28)
      - IPv6 traversal + v4-in-v6 embedding (ipv6-32, country)
      - realistic Country schema extraction (country.iso_code + names)
      - v6-in-v4-db rejection, closed-reader rejection
      - dot-call + colon-call ergonomics

    Run from the repo root:
      lua5.4 tests/unit/mmdb_test.lua

]]--

local FIXDIR = "tests/unit/fixtures/mmdb/"

----------------------------------------------------------------------
-- use() shim: core/mmdb.lua + core/ipmatch.lua run under init.lua's
-- restricted env in the hub. Here we hand them the real stdlib. `io`
-- is the REAL io because the reader opens actual fixture files.
----------------------------------------------------------------------

local _real = {
    type = type, tonumber = tonumber, tostring = tostring, error = error,
    pcall = pcall, setmetatable = setmetatable, string = string,
    table = table, io = io, ipairs = ipairs,
}
local _loaded_ipmatch
local function use_stub( name )
    if name == "ipmatch" then return _loaded_ipmatch end
    local v = _real[ name ]
    if v ~= nil then return v end
    error( "mmdb_test shim: missing dep " .. tostring( name ) )
end

_G.use = use_stub
_loaded_ipmatch = assert( loadfile( "core/ipmatch.lua" ) )( )
local mmdb = assert( loadfile( "core/mmdb.lua" ) )( )

----------------------------------------------------------------------
-- Tiny harness
----------------------------------------------------------------------

local _passes, _fails = 0, 0
local function eq( what, got, want )
    if got == want then _passes = _passes + 1
    else
        _fails = _fails + 1
        io.stderr:write( string.format( "FAIL: %s\n  got:  %s\n  want: %s\n",
            what, tostring( got ), tostring( want ) ) )
    end
end
local function truthy( what, v )
    if v then _passes = _passes + 1
    else _fails = _fails + 1; io.stderr:write( "FAIL: " .. what .. " got=" .. tostring( v ) .. "\n" ) end
end
local function falsy( what, v )
    if not v then _passes = _passes + 1
    else _fails = _fails + 1; io.stderr:write( "FAIL: " .. what .. " got=" .. tostring( v ) .. "\n" ) end
end
local function near( what, got, want )
    if type( got ) == "number" and math.abs( got - want ) < 1e-9 then _passes = _passes + 1
    else
        _fails = _fails + 1
        io.stderr:write( string.format( "FAIL: %s\n  got:  %s\n  want: ~%s\n",
            what, tostring( got ), tostring( want ) ) )
    end
end
local function arr_eq( what, got, want )
    if type( got ) ~= "table" then
        _fails = _fails + 1
        io.stderr:write( "FAIL: " .. what .. " not a table (got " .. tostring( got ) .. ")\n" )
        return
    end
    if #got ~= #want then
        _fails = _fails + 1
        io.stderr:write( string.format( "FAIL: %s length got=%d want=%d\n", what, #got, #want ) )
        return
    end
    for i = 1, #want do
        if got[ i ] ~= want[ i ] then
            _fails = _fails + 1
            io.stderr:write( string.format( "FAIL: %s[%d] got=%s want=%s\n",
                what, i, tostring( got[ i ] ), tostring( want[ i ] ) ) )
            return
        end
    end
    _passes = _passes + 1
end

local function must_open( name )
    local r, err = mmdb.open( FIXDIR .. name )
    assert( r, "open " .. name .. " failed: " .. tostring( err ) )
    return r
end

----------------------------------------------------------------------
-- open(): error returns (bad arg / missing / non-MMDB)
----------------------------------------------------------------------

do
    local r, err = mmdb.open( nil )
    falsy( "open(nil) returns nil", r ); truthy( "open(nil) has err", err )

    r, err = mmdb.open( "" )
    falsy( "open('') returns nil", r ); truthy( "open('') has err", err )

    r, err = mmdb.open( FIXDIR .. "does-not-exist.mmdb" )
    falsy( "open(missing) returns nil", r ); truthy( "open(missing) has err", err )

    -- README.md contains the ASCII "MaxMind.com" but NOT the binary
    -- \xab\xcd\xef marker prefix, so it must be rejected cleanly.
    r, err = mmdb.open( FIXDIR .. "README.md" )
    falsy( "open(non-MMDB) returns nil", r )
    truthy( "open(non-MMDB) has err", err )
end

----------------------------------------------------------------------
-- Metadata across all three record sizes
----------------------------------------------------------------------

do
    local dec = must_open( "MaxMind-DB-test-decoder.mmdb" )
    eq( "decoder ip_version",  dec.metadata.ip_version, 6 )
    eq( "decoder record_size", dec.metadata.record_size, 24 )
    eq( "decoder node_count",  dec.metadata.node_count, 426 )
    eq( "decoder db_type",     dec.metadata.database_type, "MaxMind DB Decoder Test" )

    local v4 = must_open( "MaxMind-DB-test-ipv4-28.mmdb" )
    eq( "ipv4-28 ip_version",  v4.metadata.ip_version, 4 )
    eq( "ipv4-28 record_size", v4.metadata.record_size, 28 )

    local v6 = must_open( "MaxMind-DB-test-ipv6-32.mmdb" )
    eq( "ipv6-32 ip_version",  v6.metadata.ip_version, 6 )
    eq( "ipv6-32 record_size", v6.metadata.record_size, 32 )

    local co = must_open( "GeoLite2-Country-Test.mmdb" )
    eq( "country ip_version",  co.metadata.ip_version, 6 )
    eq( "country record_size", co.metadata.record_size, 28 )
    eq( "country db_type",     co.metadata.database_type, "GeoLite2-Country" )
end

----------------------------------------------------------------------
-- Full data-type decode (decoder.mmdb). Golden values from the
-- reference maxminddb reader.
----------------------------------------------------------------------

do
    local r = must_open( "MaxMind-DB-test-decoder.mmdb" )
    local rec = r:lookup( "1.1.1.0" )
    truthy( "decoder 1.1.1.0 hit", rec )
    if rec then
        arr_eq( "decoder array",   rec.array, { 1, 2, 3 } )
        eq( "decoder boolean",     rec.boolean, true )
        eq( "decoder bytes len",   rec.bytes and #rec.bytes, 4 )
        eq( "decoder bytes value", rec.bytes, "\0\0\0\42" )
        near( "decoder double",    rec.double, 42.123456 )
        near( "decoder float",     rec.float, 1.100000023841858 )
        eq( "decoder int32",       rec.int32, -268435456 )
        eq( "decoder uint16",      rec.uint16, 100 )
        eq( "decoder uint32",      rec.uint32, 268435456 )
        eq( "decoder uint64",      rec.uint64, 1152921504606846976 )
        eq( "decoder uint128 hex", rec.uint128, "1" .. string.rep( "0", 30 ) )   -- 2^120
        eq( "decoder utf8_string", rec.utf8_string, "unicode! \xe2\x98\xaf - \xe2\x99\xab" )
        truthy( "decoder map",     rec.map )
        if rec.map then
            truthy( "decoder map.mapX", rec.map.mapX )
            if rec.map.mapX then
                arr_eq( "decoder map.mapX.arrayX", rec.map.mapX.arrayX, { 7, 8, 9 } )
                eq( "decoder map.mapX.utf8_stringX", rec.map.mapX.utf8_stringX, "hello" )
            end
        end
    end

    -- All-zero / empty variant.
    local z = r:lookup( "0.0.0.0" )
    truthy( "decoder 0.0.0.0 hit", z )
    if z then
        eq( "decoder empty array len",  z.array and #z.array, 0 )
        eq( "decoder empty boolean",    z.boolean, false )
        eq( "decoder empty bytes",      z.bytes, "" )
        eq( "decoder empty uint16",     z.uint16, 0 )
        eq( "decoder empty uint32",     z.uint32, 0 )
        eq( "decoder empty int32",      z.int32, 0 )
        eq( "decoder empty uint128",    z.uint128, "0" )
        eq( "decoder empty utf8_string", z.utf8_string, "" )
        truthy( "decoder empty map is table", type( z.map ) == "table" )
    end

    -- v4-in-v6 embedding is exercised by the plain "1.1.1.0" lookup
    -- above: this DB is ip_version 6, so a v4 lookup already traverses
    -- the ::/96 subtree via mmdb's ZERO12 prefix branch (see also the
    -- country-DB v4 hits below). We do NOT assert the equivalent v6
    -- literal "::1.1.1.0" here because ipmatch only parses the
    -- v4-mapped form "::ffff:a.b.c.d", not the deprecated
    -- v4-compatible "::a.b.c.d" (RFC 4291 2.5.5.1) - real clients never
    -- present the latter, so it is not an mmdb concern.
end

----------------------------------------------------------------------
-- IPv4-native traversal + 28-bit records + clean miss (ipv4-28)
----------------------------------------------------------------------

do
    local r = must_open( "MaxMind-DB-test-ipv4-28.mmdb" )
    local a = r:lookup( "1.1.1.1" );  eq( "ipv4-28 1.1.1.1", a and a.ip, "1.1.1.1" )
    local b = r:lookup( "1.1.1.2" );  eq( "ipv4-28 1.1.1.2", b and b.ip, "1.1.1.2" )
    local c = r:lookup( "1.1.1.3" );  eq( "ipv4-28 1.1.1.3 (/31 shares .2)", c and c.ip, "1.1.1.2" )
    local d = r:lookup( "1.1.1.16" ); eq( "ipv4-28 1.1.1.16", d and d.ip, "1.1.1.16" )

    local miss, err = r:lookup( "2.2.2.2" )
    falsy( "ipv4-28 2.2.2.2 clean miss (nil)", miss )
    falsy( "ipv4-28 2.2.2.2 no error on miss", err )

    falsy( "ipv4-28 255.255.255.255 miss", r:lookup( "255.255.255.255" ) )

    -- v6 lookup against a v4-only DB is an error, not a miss.
    local v6r, v6err = r:lookup( "::1" )
    falsy( "ipv4-28 v6 lookup returns nil", v6r )
    truthy( "ipv4-28 v6 lookup returns err", v6err )

    -- dot-call ergonomics.
    local dot = r.lookup( "1.1.1.1" ); eq( "ipv4-28 dot-call", dot and dot.ip, "1.1.1.1" )
end

----------------------------------------------------------------------
-- IPv6 traversal + 32-bit records + v4-in-v6 miss path (ipv6-32)
----------------------------------------------------------------------

do
    local r = must_open( "MaxMind-DB-test-ipv6-32.mmdb" )
    local a = r:lookup( "::1:ffff:ffff" ); eq( "ipv6-32 ::1:ffff:ffff", a and a.ip, "::1:ffff:ffff" )
    local b = r:lookup( "::2:0:1" );       eq( "ipv6-32 ::2:0:1 (/122 net ::2:0:0)", b and b.ip, "::2:0:0" )

    -- v4-in-v6 traversal reaches the ::/96 subtree; this DB has no v4
    -- data there, so a clean miss (and, critically, no crash in the
    -- start-node embedding).
    local m4, e4 = r:lookup( "1.1.1.1" )
    falsy( "ipv6-32 v4-in-v6 clean miss", m4 )
    falsy( "ipv6-32 v4-in-v6 no error", e4 )

    falsy( "ipv6-32 ::1:0:0 miss", r:lookup( "::1:0:0" ) )
end

----------------------------------------------------------------------
-- Realistic Country schema + v4-in-v6 hits (GeoLite2-Country-Test)
----------------------------------------------------------------------

do
    local r = must_open( "GeoLite2-Country-Test.mmdb" )

    local gb = r:lookup( "2.125.160.216" )
    truthy( "country 2.125.160.216 hit", gb )
    if gb then
        eq( "country GB iso_code",   gb.country and gb.country.iso_code, "GB" )
        eq( "country GB name en",    gb.country and gb.country.names and gb.country.names.en, "United Kingdom" )
        eq( "country GB continent",  gb.continent and gb.continent.code, "EU" )
        eq( "country GB reg_country", gb.registered_country and gb.registered_country.iso_code, "FR" )
    end

    -- IPv4 lookups against the v6 tree (the common GeoIP case).
    local se = r:lookup( "89.160.20.128" )
    local us_v4 = r:lookup( "81.2.69.160" )
    local jp = r:lookup( "2001:218::1" )
    eq( "country 81.2.69.160 (v4) GB",   us_v4 and us_v4.country.iso_code, "GB" )
    eq( "country 89.160.20.128 (v4) SE", se and se.country.iso_code, "SE" )
    eq( "country 2001:218::1 (v6) JP",   jp and jp.country.iso_code, "JP" )

    falsy( "country 10.0.0.1 miss",  r:lookup( "10.0.0.1" ) )
    falsy( "country 214.0.0.0 miss", r:lookup( "214.0.0.0" ) )
end

----------------------------------------------------------------------
-- close(): a closed reader rejects lookups
----------------------------------------------------------------------

do
    local r = must_open( "MaxMind-DB-test-ipv4-28.mmdb" )
    truthy( "pre-close lookup works", r:lookup( "1.1.1.1" ) )
    eq( "close returns true", r:close( ), true )
    local res, err = r:lookup( "1.1.1.1" )
    falsy( "post-close lookup nil", res )
    truthy( "post-close lookup err", err )
end

----------------------------------------------------------------------
-- Adversarial / corrupt-input hardening. These craft raw bytes (a tiny
-- MMDB encoder local to the test) and assert mmdb.open degrades to a
-- clean (nil, err) - it runs on the hub boot / refresh path, so a
-- crash / hang / OOM / broken-reader here would take down the hub.
----------------------------------------------------------------------

do
    local MARKER = "\xab\xcd\xef" .. "MaxMind.com"

    local _seq = 0
    local _tmp = { }
    local function write_temp( bytes )
        _seq = _seq + 1
        local dir = os.getenv( "TMPDIR" ) or os.getenv( "TEMP" ) or os.getenv( "TMP" ) or "."
        local path = dir .. "/mmdb_test_" .. _seq .. ".bin"
        local f = assert( io.open( path, "wb" ), "cannot open temp file " .. path )
        f:write( bytes ); f:close( )
        _tmp[ #_tmp + 1 ] = path
        return path
    end

    -- Minimal MMDB data-format encoders (test-only; the reader is
    -- validated against MaxMind's real files above - these just build
    -- hostile shapes).
    local function be_bytes( n, width )
        local t = { }
        for i = width, 1, -1 do t[ i ] = string.char( n & 0xff ); n = n >> 8 end
        return table.concat( t )
    end
    local function uint_field( n, width )        -- extended uint64, `width` bytes
        return string.char( width, 0x02 ) .. be_bytes( n, width )
    end
    local function str_field( s )                -- utf8 string (len < 29)
        return string.char( 0x40 | #s ) .. s
    end
    local function array_header( size )          -- extended array (type 11 -> ext byte 4)
        if size < 29 then
            return string.char( size, 0x04 )
        elseif size < 285 then
            return string.char( 29, 0x04, size - 29 )
        else
            local v = size - 285
            return string.char( 30, 0x04, ( v >> 8 ) & 0xff, v & 0xff )
        end
    end
    local function meta_map( node_count, nc_width, record_size, ip_version )
        return string.char( 0xE0 | 3 )           -- map, 3 entries
            .. str_field( "node_count" )  .. uint_field( node_count, nc_width )
            .. str_field( "record_size" ) .. uint_field( record_size, 1 )
            .. str_field( "ip_version" )  .. uint_field( ip_version, 1 )
    end

    -- Zero-byte file.
    do
        local zr, zerr = mmdb.open( write_temp( "" ) )
        falsy( "open(zero-byte) nil", zr ); truthy( "open(zero-byte) err", zerr )
    end

    -- Non-MMDB bytes (no marker).
    do
        local nr, nerr = mmdb.open( write_temp( "not an mmdb file at all" ) )
        falsy( "open(no-marker) nil", nr ); truthy( "open(no-marker) err", nerr )
    end

    -- Truncated: node_count small enough to pass the size bound but
    -- node_count * node_size overshoots the file -> data_section_start >
    -- #data must reject cleanly (not build a reader over a phantom tree).
    do
        local buf = MARKER .. meta_map( 30, 1, 32, 6 )   -- tree would be 240 bytes; file ~60
        local tr, terr = mmdb.open( write_temp( buf ) )
        falsy( "open(truncated tree) nil", tr ); truthy( "open(truncated tree) err", terr )
    end

    -- F2 regression: a hostile node_count near 2^61 makes node_count *
    -- node_size (x8) overflow 64-bit and wrap search_tree_size negative,
    -- which slipped past the truncation check and yielded a BROKEN
    -- reader (open returned a truthy object) pre-fix. Post-fix the
    -- node_count > #data guard rejects it. This assertion FAILS on the
    -- unpatched reader (which returned a reader) and PASSES patched.
    do
        local buf = MARKER .. meta_map( 1 << 61, 8, 32, 6 )
        local orr, oerr = mmdb.open( write_temp( buf ) )
        falsy( "open(node_count overflow) returns nil (F2)", orr )
        truthy( "open(node_count overflow) err", oerr )
    end

    -- F1 regression: decode-amplification bomb. A top array of K
    -- pointer elements all pointing at one shared inner array of N tiny
    -- elements is K*N decode ops at shallow (constant) depth, so the
    -- depth guard never fires. Only the total-op budget stops it. The
    -- bomb lives in the metadata region (decoded at open() before
    -- validation), pointer base = metadata start. Unpatched, open()
    -- fully decodes ~1.6M nodes and then fails validation with a
    -- "node_count invalid" error (no "budget" text) -> the budget
    -- assertion below FAILS pre-fix and PASSES patched.
    do
        local K, N = 400, 4000                   -- 1.6M ops > MAX_DECODE_OPS (1e6)
        local top = array_header( K )
        local inner_off = #top + K * 2           -- ss=0 pointer is 2 bytes each
        assert( inner_off <= 0x7ff, "test bomb inner offset must fit ss=0 pointer" )
        local ptr = string.char( 0x20 | ( ( inner_off >> 8 ) & 0x7 ), inner_off & 0xff )
        local bomb = top .. string.rep( ptr, K )
                  .. array_header( N ) .. string.rep( "\xA0", N )
        local br, berr = mmdb.open( write_temp( MARKER .. bomb ) )
        falsy( "open(amplification bomb) nil", br )
        truthy( "open(amplification bomb) err", berr )
        truthy( "open(amplification bomb) hits op budget (F1)", berr and berr:find( "budget" ) )
    end

    for _, p in ipairs( _tmp ) do os.remove( p ) end
end

----------------------------------------------------------------------

io.stderr:write( string.format( "\nmmdb_test: %d passed, %d failed\n", _passes, _fails ) )
os.exit( _fails == 0 and 0 or 1 )
